name: Infrastructure Pipeline

on:
  push:
    branches:
      - dev
      - prod

jobs:
  setup:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        run: az login

      - name: Change to Environment Directory
        run: cd environments/${{ github.ref == 'refs/heads/dev' && 'dev' || (github.ref == 'refs/heads/main' && 'prod' || '') }}

      - name: Run Terraform Init
        run: |
          source store-tfstate.sh "${{ secrets.TENANT_ID }}" \
                                  "${{ secrets.SUBSCRIPTION_ID }}" \
                                  "${{ secrets.USER_EMAIL }}" \
                                  "${{ secrets.RESOURCE_GROUP_NAME }}" \
                                  "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
                                  "${{ secrets.CONTAINER_NAME }}" \
                                  "${{ secrets.KEYVAULT_NAME }}" \
                                  "${{ secrets.SECRET_NAME }}" \
                                  "${{ secrets.LOCATION }}"

          terraform init -backend-config="resource_group_name=$RESOURCE_GROUP_NAME" \
               -backend-config="storage_account_name=$STORAGE_ACCOUNT_NAME" \
               -backend-config="container_name=$CONTAINER_NAME" \
               -reconfigure

      - name: Run Terraform Plan
        run: terraform plan -var="subscription_id=$SUBSCRIPTION_ID"

      - name: Run Terraform Apply
        run: terraform apply -auto-approve -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"

  teardown:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Run Terraform Destroy
        run: |
          cd environments/dev/
          terraform init -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
                         -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
                         -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
                         -reconfigure
          terraform destroy -auto-approve -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"
